spring:
  application:
    name: ai-page-gen-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_page_gen
    username: root
    password: 123456
  # 指定生效为application-local配置，激活本地配置
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 文档：http://localhost:8123/api/doc.html
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: "/**"
      packages-to-scan: com.miu.codemain.controller
# knife4j：基于Swagger接口文档的增强工具，适用于SpringBoot，可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      #      strict-json-schema: true
      response-format: json_object
      max-tokens: 8192
      log-requests: true
      log-responses: true
      max-retries: 3
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true